<h4>KO</h4>
<div data-bind="scope: 'example'" id="example">
    First Name: <p data-bind="text: firstName"></p>
    <br>Last Name: <p data-bind="text: lastName"></p>
    <br><p data-bind="text: fullName">123</p>
</div>
<script type="text/x-magento-init">
        {
            "*": {
               "Magento_Ui/js/core/app": {
                   "components": {
                       "example": {
                           "component": "KTPL_Training/js/example"
                       }
                   }
               }
            }
        }

</script>